-- =========================================================
-- Supabase PostgreSQL Database Schema with Per-User RLS
-- Project: Personal Life OS & To-Do PWA
-- =========================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. TODOS TABLE
create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid() not null,
  title text not null,
  description text,
  scope text check (scope in ('daily', 'weekly', 'monthly')) not null default 'daily',
  category text not null default 'Pekerjaan',
  due_date date not null,
  due_time text,
  completed boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists todos_user_id_idx on public.todos(user_id);
create index if not exists todos_due_date_idx on public.todos(due_date);
create index if not exists todos_scope_idx on public.todos(scope);

alter table public.todos enable row level security;

create policy "Users can manage their own todos"
  on public.todos for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- 2. WISHLISTS TABLE
create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid() not null,
  title text not null,
  type text check (type in ('place', 'item')) not null,
  target_cost numeric not null default 0,
  current_saved numeric not null default 0,
  notes text,
  target_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists wishlists_user_id_idx on public.wishlists(user_id);
create index if not exists wishlists_type_idx on public.wishlists(type);

alter table public.wishlists enable row level security;

create policy "Users can manage their own wishlists"
  on public.wishlists for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- 3. DAILY LOGS TABLE
create table if not exists public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid() not null,
  date date not null,
  quick_notes text default '',
  daily_wins text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint daily_logs_user_date_unique unique (user_id, date)
);

create index if not exists daily_logs_user_id_idx on public.daily_logs(user_id);
create index if not exists daily_logs_date_idx on public.daily_logs(date);

alter table public.daily_logs enable row level security;

create policy "Users can manage their own daily logs"
  on public.daily_logs for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
